#!/usr/bin/expect -f

#echo $1
set user [lindex $argv 0]
set ip [lindex $argv 1]
set password [lindex $argv 2]
spawn ssh $user@$ip
expect {
"yes/no" {send "yes\r"; exp_continue}
"password" {send "$password\r"}
}
interact
